apiVersion: v1
kind: Service
metadata:
  name: redis-headless
spec:
  clusterIP: None
  selector:
    app: redis
  ports:
  - port: {{ .Values.redis.service.port }}
    name: redis
    targetPort: {{ .Values.redis.service.port }}
