apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  serviceName: redis-headless

  replicas: {{ .Values.redis.replicas }}

  selector:
    matchLabels:
      app: redis

  template:
    metadata:
      labels:
        app: redis

    spec:
      containers:
        - name: redis
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}

          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-auth
                  key: password

          ports:
            - containerPort: {{ .Values.redis.service.port }}

          command:
            - /bin/sh
            - -c

          args:
            - >
              redis-server
              --appendonly yes
              {{- if .Values.redis.auth.enabled }}
              --requirepass "$REDIS_PASSWORD"
              {{- end }}

          volumeMounts:
            - name: redis-data
              mountPath: /data
          
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}

  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.redis.persistence.size }}







