# Default values for redis-ce.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

redis:

  sentinel:
    enabled: true

  replicas: 3

  image:
    repository: redis
    tag: "8"
    pullPolicy: IfNotPresent

  service:
    port: 6379

  persistence:
    enabled: true
    size: 8Gi

  auth:
    enabled: true
    password: "ChangeMe123!"

  resources:
    requests:
      cpu: 100m
      memory: 256Mi

    limits:
      cpu: 500m
      memory: 1Gi

# Monitoring
metrics:
  enabled: true

  image:
    repository: oliver006/redis_exporter
    tag: latest

  port: 9121
